name = "anime-decrypto-api"
main = "worker/index.ts"
compatibility_date = "2026-06-01"

[[durable_objects.bindings]]
name = "ROOM_OBJECTS"
class_name = "RoomDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDurableObject"]

[[d1_databases]]
binding = "DB"
database_name = "anime_decrypto"
database_id = "8544a886-dd92-4d10-8658-b9c58b3a621e"
migrations_dir = "d1/migrations"

[vars]
ALLOWED_ORIGIN = "https://anime-decrypto.pages.dev"
